### ISSUE TITLE
Webiste: Index

### ISSUE THREAD

**Issue by MarcTschudin** [wearebeautiful/wearebeautiful.info#26]
!) **del _ del** We create 3D models of human genitals with the aim of breaking taboos, educating at a global level, and improving our users self-body images. **del _ del** 

?) Include "full body" and "body parts" (breasts, bellys and back sides are not genitals), if not to much for the short description.

!) "...Our photographer **take** photos..."

!) These 3D models **? are ?** freely available for viewing on this site and for downloading so that you may print them on your own 3D printer. 

?) We hope to show that there is no normal and that we humans are all beautiful **? , no matter what our bodies have experienced or beauty standards dictate. ?**
Ne needs to use those words, but I like the idea of communicating that here.

Button: I agree to see models of human genitals!
?: We also have full body scanns: "I agree to see models of nude humans and (their) genitals!"
not sure about "their"

Button pressed: Transition works fine on OSX 10.11.6 , FF 75.0

in general: missing "," in the text.

**Comment by mayhem** [comment]
I think these have all been addressed now. If something is still not sufficient, open another issue.
